import os
import sys
import math
import json
import struct
import base64
import pandas as pd
from dataclasses import dataclass
from bitstring import BitArray, ConstBitStream

from ftyp import *
from moof import *
from moov import *
from moov_subatom import *
from nal_parser import *
from featureExtraction import *

AtomDict = {}
boxSequence = []
codec_id = []


def h264NALUExtraction(video_path, sps_rbsp, pps_rbsp):
    fileName = os.path.basename(video_path)
    if sps_rbsp.vui.order["hrd"]:
        cpb_cnt_minus1 = sps_rbsp.vui.order["hrd"].order["cpb_cnt_minus1"],
        bit_rate_scale = sps_rbsp.vui.order["hrd"].order["bit_rate_scale"],
        cpb_siz_scale = sps_rbsp.vui.order["hrd"].order["cpb_size_scale"],
        bit_rate_value_minus1 = sps_rbsp.vui.order["hrd"].order["bit_rate_value_minus1"],
        cpb_size_value_minus1 = sps_rbsp.vui.order["hrd"].order["cpb_size_value_minus1"],
        cbr_flag = sps_rbsp.vui.order["hrd"].order["cbr_flag"],
        initial_cpb_removal_delay_length_minus1 = sps_rbsp.vui.order["hrd"].order["initial_cpb_removal_delay_length_minus1"],
        cpb_removal_delay_length_minus1 = sps_rbsp.vui.order["hrd"].order["cpb_removal_delay_length_minus1"],
        dpb_output_delay_length_minus1 = sps_rbsp.vui.order["hrd"].order["dpb_output_delay_length_minus1"],
        time_offset_length = sps_rbsp.vui.order["hrd"].order["time_offset_length"]
    else:
        cpb_cnt_minus1 =None
        bit_rate_scale =None
        cpb_siz_scale =None
        bit_rate_value_minus1 =None
        cpb_size_value_minus1 =None
        cbr_flag =None
        initial_cpb_removal_delay_length_minus1 =None
        cpb_removal_delay_length_minus1 =None
        dpb_output_delay_length_minus1 =None
        time_offset_length =None

    result = {
        'file_name': f'{fileName}',
        # SPS
        'profile_idc':sps_rbsp.order["profile_idc"], 
        "constraint_set0_flag": sps_rbsp.order["constraint_set0_flag"],
        "constraint_set1_flag": sps_rbsp.order["constraint_set1_flag"],
        "constraint_set2_flag": sps_rbsp.order["constraint_set2_flag"],
        "constraint_set3_flag": sps_rbsp.order["constraint_set3_flag"],
        "constraint_set4_flag": sps_rbsp.order["constraint_set4_flag"],
        "constraint_set5_flag": sps_rbsp.order["constraint_set5_flag"],
        "level_idc": sps_rbsp.order["level_idc"],
        "seq_parameter_set_id": sps_rbsp.order["seq_parameter_set_id"],
        "chroma_format_idc": sps_rbsp.order["chroma_format_idc"],  #discord
        "separate_colour_plane_flag": sps_rbsp.order["separate_colour_plane_flag"],
        "bit_depth_luma_minus8": sps_rbsp.order["bit_depth_luma_minus8"],
        "bit_depth_chroma_minus8": sps_rbsp.order["bit_depth_chroma_minus8"],
        "qpprime_y_zero_transform_bypass_flag": sps_rbsp.order["qpprime_y_zero_transform_bypass_flag"],
        "seq_scaling_matrix_present_flag": sps_rbsp.order["seq_scaling_matrix_present_flag"],
        "seq_scaling_list_present_flag": sps_rbsp.order["seq_scaling_list_present_flag"],
        "delta_scale": sps_rbsp.order["delta_scale"],
        "log2_max_frame_num_minus4": sps_rbsp.order["log2_max_frame_num_minus4"],
        "pic_order_cnt_type": sps_rbsp.order["pic_order_cnt_type"],
        "log2_max_pic_order_cnt_lsb_minus4": sps_rbsp.order["log2_max_pic_order_cnt_lsb_minus4"],
        "delta_pic_order_always_zero_flag": sps_rbsp.order["delta_pic_order_always_zero_flag"],
        "offset_for_non_ref_pic": sps_rbsp.order["offset_for_non_ref_pic"],
        "offset_for_top_to_bottom_filed": sps_rbsp.order["offset_for_top_to_bottom_filed"],
        "num_ref_frames_in_pic_order_cnt_cycle": sps_rbsp.order["num_ref_frames_in_pic_order_cnt_cycle"],
        "offset_for_ref_frame": sps_rbsp.order["offset_for_ref_frame"],
        "num_ref_frames": sps_rbsp.order["num_ref_frames"],
        "gaps_in_frame_num_value_allowed_flag": sps_rbsp.order["gaps_in_frame_num_value_allowed_flag"],
        "pic_width_in_mbs_minus_1": sps_rbsp.order["pic_width_in_mbs_minus_1"],
        "pic_height_in_map_units_minus_1": sps_rbsp.order["pic_height_in_map_units_minus_1"],
        "frame_mbs_only_flag": sps_rbsp.order["frame_mbs_only_flag"],
        "mb_adapative_frame_field_flag": sps_rbsp.order["mb_adapative_frame_field_flag"],
        "direct_8x8_inference_flag": sps_rbsp.order["direct_8x8_inference_flag"],
        "frame_cropping_flag": sps_rbsp.order["frame_cropping_flag"],
        "frame_crop_left_offset": sps_rbsp.order["frame_crop_left_offset"],
        "frame_crop_right_offset": sps_rbsp.order["frame_crop_right_offset"],
        "frame_crop_top_offset": sps_rbsp.order["frame_crop_top_offset"],
        "frame_crop_bottom_offset": sps_rbsp.order["frame_crop_bottom_offset"],
        "vui_parameters_present_flag": sps_rbsp.order["vui_parameters_present_flag"],

        #VUI
        "aspect_ratio_info_present_flag": sps_rbsp.vui.order["aspect_ratio_info_present_flag"],
        "aspect_ratio_idc": sps_rbsp.vui.order["aspect_ratio_idc"],
        "sar_width": sps_rbsp.vui.order["sar_width"],
        "sar_height": sps_rbsp.vui.order["sar_height"],
        "overscan_info_present_flag": sps_rbsp.vui.order["overscan_info_present_flag"],
        "overscan_appropriate_flag": sps_rbsp.vui.order["overscan_appropriate_flag"],
        "video_signal_type_present_flag": sps_rbsp.vui.order["video_signal_type_present_flag"],
        "video_format": sps_rbsp.vui.order["video_format"],
        "video_full_range_flag": sps_rbsp.vui.order["video_full_range_flag"],
        "colour_description_present_flag": sps_rbsp.vui.order["colour_description_present_flag"],
        "colour_primaries": sps_rbsp.vui.order["colour_primaries"],
        "transfer_characteristics": sps_rbsp.vui.order["transfer_characteristics"],
        "matrix_coefficients": sps_rbsp.vui.order["matrix_coefficients"],
        "chroma_loc_info_present_flag": sps_rbsp.vui.order["chroma_loc_info_present_flag"],
        "chroma_sample_loc_type_top_field": sps_rbsp.vui.order["chroma_sample_loc_type_top_field"],
        "chroma_sample_loc_type_bottom_field": sps_rbsp.vui.order["chroma_sample_loc_type_bottom_field"],
        "timing_info_present_flag": sps_rbsp.vui.order["timing_info_present_flag"],
        "num_units_in_tick": sps_rbsp.vui.order["num_units_in_tick"],
        "time_scale": sps_rbsp.vui.order["time_scale"],
        "fixed_frame_rate_flag": sps_rbsp.vui.order["fixed_frame_rate_flag"],
        "nal_hrd_parameters_present_flag": sps_rbsp.vui.order["nal_hrd_parameters_present_flag"],
        "cpb_cnt_minus1": cpb_cnt_minus1,
        "bit_rate_scale": bit_rate_scale,
        "cpb_siz_scale": cpb_siz_scale,
        "bit_rate_value_minus1": bit_rate_value_minus1,
        "cpb_size_value_minus1": cpb_size_value_minus1,
        "cbr_flag": cbr_flag,
        "initial_cpb_removal_delay_length_minus1": initial_cpb_removal_delay_length_minus1,
        "cpb_removal_delay_length_minus1": cpb_removal_delay_length_minus1,
        "dpb_output_delay_length_minus1": dpb_output_delay_length_minus1,
        "time_offset_length": time_offset_length,
        "vcl_hrd_parameters_present_flag": sps_rbsp.vui.order["vcl_hrd_parameters_present_flag"],
        "low_delay_hrd_flag": sps_rbsp.vui.order["low_delay_hrd_flag"],
        "pic_struct_present_flag": sps_rbsp.vui.order["pic_struct_present_flag"],
        "bitstream_restriction_flag": sps_rbsp.vui.order["bitstream_restriction_flag"],
        "motion_vectors_over_pic_boundaries_flag": sps_rbsp.vui.order["motion_vectors_over_pic_boundaries_flag"],
        "max_bytes_per_pic_denom": sps_rbsp.vui.order["max_bytes_per_pic_denom"],
        "max_bits_per_mb_denom": sps_rbsp.vui.order["max_bits_per_mb_denom"],
        "log2_max_mv_length_horizontal": sps_rbsp.vui.order["log2_max_mv_length_horizontal"],
        "log2_max_mv_length_vertical": sps_rbsp.vui.order["log2_max_mv_length_vertical"],
        "num_reorder_frames": sps_rbsp.vui.order["num_reorder_frames"],
        "max_dec_frame_buffering": sps_rbsp.vui.order["max_dec_frame_buffering"],
        
        # PPS
        "pic_parameter_set_id":pps_rbsp.order["pic_parameter_set_id"],
        "seq_parameter_set_id":pps_rbsp.order["seq_parameter_set_id"],
        "entropy_coding_mode_flag":pps_rbsp.order["entropy_coding_mode_flag"],
        "pic_order_present_flag":pps_rbsp.order["pic_order_present_flag"],
        "num_slice_groups_minus1":pps_rbsp.order["num_slice_groups_minus1"],
        "slice_group_map_type":pps_rbsp.order["slice_group_map_type"],
        "run_length_minus1":pps_rbsp.order["run_length_minus1"],
        "top_left":pps_rbsp.order["top_left"],
        "bottom_right":pps_rbsp.order["bottom_right"],
        "slice_group_change_direction_flag":pps_rbsp.order["slice_group_change_direction_flag"],
        "slice_group_change_rate_minus1":pps_rbsp.order["slice_group_change_rate_minus1"],
        "pic_size_in_map_units_minus1":pps_rbsp.order["pic_size_in_map_units_minus1"],
        "slice_group_id":pps_rbsp.order["slice_group_id"],
        "num_ref_idx_l0_active_minus1":pps_rbsp.order["num_ref_idx_l0_active_minus1"],
        "num_ref_idx_l1_active_minus1":pps_rbsp.order["num_ref_idx_l1_active_minus1"],
        "weighted_pred_flag":pps_rbsp.order["weighted_pred_flag"],
        "weighted_bipred_idc":pps_rbsp.order["weighted_bipred_idc"],
        "pic_init_qp_minus26":pps_rbsp.order["pic_init_qp_minus26"],
        "pic_init_qs_minus26":pps_rbsp.order["pic_init_qs_minus26"],
        "chroma_qp_index_offset":pps_rbsp.order["chroma_qp_index_offset"],
        "deblocking_filter_control_present_flag":pps_rbsp.order["deblocking_filter_control_present_flag"],
        "constrained_intra_pred_flag":pps_rbsp.order["constrained_intra_pred_flag"],
        "redundant_pic_cnt_present_flag":pps_rbsp.order["redundant_pic_cnt_present_flag"]
        }
    df = pd.DataFrame([result], index=[0])
    df = df.fillna("-9999")

    if not os.path.exists('NALUFeature_h264.csv'):
        df.to_csv('NALUFeature_h264.csv', index=False, mode='w', encoding='utf-8-sig', header=True)
    else:
        df.to_csv('NALUFeature_h264.csv', index=False, mode='a', encoding='utf-8-sig', header=False)
def h265NALUExtraction(video_path, vps_rbsp, sps_rbsp, pps_rbsp):
        fileName = os.path.basename(video_path)
        result = {
            'file_name': f'{fileName}',
            #VPS
            "vps_video_parameter_set_id":vps_rbsp.order["vps_video_parameter_set_id"],
            "vps_base_layer_internal_flag":vps_rbsp.order["vps_base_layer_internal_flag"],
            "vps_base_layer_available_flag":vps_rbsp.order["vps_base_layer_available_flag"],
            "vps_max_layers_minus1":vps_rbsp.order["vps_max_layers_minus1"],
            "vps_max_sub_layers_minus1":vps_rbsp.order["vps_max_sub_layers_minus1"],
            "vps_temporalid_nesting_flag":vps_rbsp.order["vps_temporalid_nesting_flag"],
            "vps_reserved_0xffff_16bits":vps_rbsp.order["vps_reserved_0xffff_16bits"],
            #VPS->profile_tier_level
            "vps_general_profile_space":vps_rbsp.order["general_profile_space"],
            "vps_general_tier_flag":vps_rbsp.order["general_tier_flag"],
            "vps_general_profile_idc":vps_rbsp.order["general_profile_idc"],
            "vps_general_profile_compatibility_flag":vps_rbsp.order["general_profile_compatibility_flag"],
            "vps_general_progressive_source_flag":vps_rbsp.order["general_progressive_source_flag"],
            "vps_general_interlaced_source_flag":vps_rbsp.order["general_interlaced_source_flag"],
            "vps_general_non_packed_constraint_flag":vps_rbsp.order["general_non_packed_constraint_flag"],
            "vps_general_frame_only_constraint_flag":vps_rbsp.order["general_frame_only_constraint_flag"],
            "vps_general_max_12bit_constraint_flag":vps_rbsp.order["general_max_12bit_constraint_flag"],
            "vps_general_max_10bit_constraint_flag":vps_rbsp.order["general_max_10bit_constraint_flag"],
            "vps_general_max_8bit_constraint_flag":vps_rbsp.order["general_max_8bit_constraint_flag"],
            "vps_general_max_422chroma_constraint_flag":vps_rbsp.order["general_max_422chroma_constraint_flag"],
            "vps_general_max_420chroma_constraint_flag":vps_rbsp.order["general_max_420chroma_constraint_flag"],
            "vps_general_max_monochrome_constraint_flag":vps_rbsp.order["general_max_monochrome_constraint_flag"],
            "vps_general_intra_constraint_flag":vps_rbsp.order["general_intra_constraint_flag"],
            "vps_general_one_picture_only_constraint_flag_1":vps_rbsp.order["general_one_picture_only_constraint_flag_1"],
            "vps_general_lower_bit_rate_constraint_flag":vps_rbsp.order["general_lower_bit_rate_constraint_flag"],
            "vps_general_max_14bit_constraint_flag":vps_rbsp.order["general_max_14bit_constraint_flag"],
            "vps_general_reserved_zero_33bits":vps_rbsp.order["general_reserved_zero_33bits"],
            "vps_general_reserved_zero_34bits":vps_rbsp.order["general_reserved_zero_34bits"],
            "vps_general_reserved_zero_7bits":vps_rbsp.order["general_reserved_zero_7bits"],
            "vps_general_one_picture_only_constraint_flag_2": vps_rbsp.order["general_one_picture_only_constraint_flag_2"],
            "vps_general_reserved_zero_35bits":vps_rbsp.order["general_reserved_zero_35bits"],
            "vps_general_reserved_zero_43bits":vps_rbsp.order["general_reserved_zero_43bits"],
            "vps_general_inbld_flag":vps_rbsp.order["general_inbld_flag"],
            "vps_general_reserved_zero_bit":vps_rbsp.order["general_reserved_zero_bit"],
            "vps_general_level_idc":vps_rbsp.order["general_level_idc"],
            "vps_sub_layer_profile_present_flag":vps_rbsp.order["sub_layer_profile_present_flag"],
            "vps_sub_layer_level_present_flag":vps_rbsp.order["sub_layer_level_present_flag"],
            "vps_reserved_zero_2bits":vps_rbsp.order["reserved_zero_2bits"],
            "vps_sub_layer_profile_space":vps_rbsp.order["sub_layer_profile_space"],
            "vps_sub_layer_tier_flag":vps_rbsp.order["sub_layer_tier_flag"],
            "vps_sub_layer_profile_idc":vps_rbsp.order["sub_layer_profile_idc"],
            "vps_sub_layer_profile_compatibility_flag":vps_rbsp.order["sub_layer_profile_compatibility_flag"],
            "vps_sub_layer_progressive_source_flag":vps_rbsp.order["sub_layer_progressive_source_flag"],
            "vps_sub_layer_interlaced_source_flag":vps_rbsp.order["sub_layer_interlaced_source_flag"],
            "vps_sub_layer_non_packed_constraint_flag":vps_rbsp.order["sub_layer_non_packed_constraint_flag"],
            "vps_sub_layer_frame_only_constraint_flag":vps_rbsp.order["sub_layer_frame_only_constraint_flag"],
            "vps_sub_layer_max_12bit_constraint_flag":vps_rbsp.order["sub_layer_max_12bit_constraint_flag"],
            "vps_sub_layer_max_10bit_constraint_flag":vps_rbsp.order["sub_layer_max_10bit_constraint_flag"],
            "vps_sub_layer_max_8bit_constraint_flag":vps_rbsp.order["sub_layer_max_8bit_constraint_flag"],
            "vps_sub_layer_max_422chroma_constraint_flag":vps_rbsp.order["sub_layer_max_422chroma_constraint_flag"],
            "vps_sub_layer_max_420chroma_constraint_flag":vps_rbsp.order["sub_layer_max_420chroma_constraint_flag"],
            "vps_sub_layer_max_monochrome_constraint_flag":vps_rbsp.order["sub_layer_max_monochrome_constraint_flag"],
            "vps_sub_layer_intra_constraint_flag":vps_rbsp.order["sub_layer_intra_constraint_flag"],
            "vps_sub_layer_one_picture_only_constraint_flag_1":vps_rbsp.order["sub_layer_one_picture_only_constraint_flag_1"],
            "vps_sub_layer_lower_bit_rate_constraint_flag_1":vps_rbsp.order["sub_layer_lower_bit_rate_constraint_flag"],
            "vps_sub_layer_max_14bit_constraint_flag":vps_rbsp.order["sub_layer_max_14bit_constraint_flag"],
            "vps_sub_layer_reserved_zero_33bits":vps_rbsp.order["sub_layer_reserved_zero_33bits"],
            "vps_sub_layer_reserved_zero_34bits":vps_rbsp.order["sub_layer_reserved_zero_34bits"],
            "vps_sub_layer_reserved_zero_7bits":vps_rbsp.order["sub_layer_reserved_zero_7bits"],
            "vps_sub_layer_one_picture_only_constraint_flag_2":vps_rbsp.order["sub_layer_one_picture_only_constraint_flag_2"],
            "vps_sub_layer_reserved_zero_35bits":vps_rbsp.order["sub_layer_reserved_zero_35bits"],
            "vps_sub_layer_reserved_zero_43bits":vps_rbsp.order["sub_layer_reserved_zero_43bits"],
            "vps_sub_layer_inbld_flag":vps_rbsp.order["sub_layer_inbld_flag"],
            "vps_sub_layer_reserved_zero_bit":vps_rbsp.order["sub_layer_reserved_zero_bit"],
            "vps_sub_layer_level_idc":vps_rbsp.order["sub_layer_level_idc"],
            
            "vps_sub_layer_ordering_info_present_flag":vps_rbsp.order["vps_sub_layer_ordering_info_present_flag"],
            "vps_max_dec_pic_buffering_minus1":vps_rbsp.order["vps_max_dec_pic_buffering_minus1"],
            "vps_max_num_reorder_pics":vps_rbsp.order["vps_max_num_reorder_pics"],
            "vps_max_latency_increase_plus1":vps_rbsp.order["vps_max_latency_increase_plus1"],
            "vps_max_layer_id":vps_rbsp.order["vps_max_layer_id"],
            "vps_num_layer_sets_minus1":vps_rbsp.order["vps_num_layer_sets_minus1"],
            "layer_id_included_flag":vps_rbsp.order["layer_id_included_flag"],
            "vps_timing_info_present_flag":vps_rbsp.order["vps_timing_info_present_flag"],
            "vps_num_units_in_tick":vps_rbsp.order["vps_num_units_in_tick"],
            "vps_time_scale":vps_rbsp.order["vps_time_scale"],
            "vps_poc_proportional_to_timing_flag":vps_rbsp.order["vps_poc_proportional_to_timing_flag"],
            "vps_num_ticks_poc_diff_one_minus1":vps_rbsp.order["vps_num_ticks_poc_diff_one_minus1"],
            "vps_num_hrd_parameters":vps_rbsp.order["vps_num_hrd_parameters"],
            "hrd_layer_set_idx":vps_rbsp.order["hrd_layer_set_idx"],
            "cprms_present_flag":vps_rbsp.order["cprms_present_flag"],
            "hrd":vps_rbsp.order["hrd"],
            "vps_extension_flag":vps_rbsp.order["vps_extension_flag"],
            "vps_extension_data_flag":vps_rbsp.order["vps_extension_data_flag"],

            # SPS
            "sps_video_parameter_set_id":sps_rbsp.order["sps_video_parameter_set_id"],
            "sps_max_sub_layers_minus1":sps_rbsp.order["sps_max_sub_layers_minus1"],
            "sps_temporal_id_nesting_flag":sps_rbsp.order["sps_temporal_id_nesting_flag"],
            # SPS -> profile_tier_leel
            "sps_general_profile_space":sps_rbsp.order["general_profile_space"],
            "sps_general_tier_flag":sps_rbsp.order["general_tier_flag"],
            "sps_general_profile_idc":sps_rbsp.order["general_profile_idc"],
            "sps_general_profile_compatibility_flag":sps_rbsp.order["general_profile_compatibility_flag"],
            "sps_general_progressive_source_flag":sps_rbsp.order["general_progressive_source_flag"],
            "sps_general_interlaced_source_flag":sps_rbsp.order["general_interlaced_source_flag"],
            "sps_general_non_packed_constraint_flag":sps_rbsp.order["general_non_packed_constraint_flag"],
            "sps_general_frame_only_constraint_flag":sps_rbsp.order["general_frame_only_constraint_flag"],
            "sps_general_max_12bit_constraint_flag":sps_rbsp.order["general_max_12bit_constraint_flag"],
            "sps_general_max_10bit_constraint_flag":sps_rbsp.order["general_max_10bit_constraint_flag"],
            "sps_general_max_8bit_constraint_flag":sps_rbsp.order["general_max_8bit_constraint_flag"],
            "sps_general_max_422chroma_constraint_flag":sps_rbsp.order["general_max_422chroma_constraint_flag"],
            "sps_general_max_420chroma_constraint_flag":sps_rbsp.order["general_max_420chroma_constraint_flag"],
            "sps_general_max_monochrome_constraint_flag":sps_rbsp.order["general_max_monochrome_constraint_flag"],
            "sps_general_intra_constraint_flag":sps_rbsp.order["general_intra_constraint_flag"],
            "sps_general_one_picture_only_constraint_flag_1":sps_rbsp.order["general_one_picture_only_constraint_flag_1"],
            "sps_general_lower_bit_rate_constraint_flag":sps_rbsp.order["general_lower_bit_rate_constraint_flag"],
            "sps_general_max_14bit_constraint_flag":sps_rbsp.order["general_max_14bit_constraint_flag"],
            "sps_general_reserved_zero_33bits":sps_rbsp.order["general_reserved_zero_33bits"],
            "sps_general_reserved_zero_34bits":sps_rbsp.order["general_reserved_zero_34bits"],
            "sps_general_reserved_zero_7bits":sps_rbsp.order["general_reserved_zero_7bits"],
            "sps_general_one_picture_only_constraint_flag_2":sps_rbsp.order["general_one_picture_only_constraint_flag_2"],
            "sps_general_reserved_zero_35bits":sps_rbsp.order["general_reserved_zero_35bits"],
            "sps_general_reserved_zero_43bits":sps_rbsp.order["general_reserved_zero_43bits"],
            "sps_general_inbld_flag":sps_rbsp.order["general_inbld_flag"],
            "sps_general_reserved_zero_bit":sps_rbsp.order["general_reserved_zero_bit"],
            "sps_general_level_idc":sps_rbsp.order["general_level_idc"],
            "sps_sub_layer_profile_present_flag":sps_rbsp.order["sub_layer_profile_present_flag"],
            "sps_sub_layer_level_present_flag":sps_rbsp.order["sub_layer_level_present_flag"],
            "sps_reserved_zero_2bits":sps_rbsp.order["reserved_zero_2bits"],
            "sps_sub_layer_profile_space":sps_rbsp.order["sub_layer_profile_space"],
            "sps_sub_layer_tier_flag":sps_rbsp.order["sub_layer_tier_flag"],
            "sps_sub_layer_profile_idc":sps_rbsp.order["sub_layer_profile_idc"],
            "sps_sub_layer_profile_compatibility_flag":sps_rbsp.order["sub_layer_profile_compatibility_flag"],
            "sps_sub_layer_progressive_source_flag":sps_rbsp.order["sub_layer_progressive_source_flag"],
            "sps_sub_layer_interlaced_source_flag":sps_rbsp.order["sub_layer_interlaced_source_flag"],
            "sps_sub_layer_non_packed_constraint_flag":sps_rbsp.order["sub_layer_non_packed_constraint_flag"],
            "sps_sub_layer_frame_only_constraint_flag":sps_rbsp.order["sub_layer_frame_only_constraint_flag"],
            "sps_sub_layer_max_12bit_constraint_flag":sps_rbsp.order["sub_layer_max_12bit_constraint_flag"],
            "sps_sub_layer_max_10bit_constraint_flag":sps_rbsp.order["sub_layer_max_10bit_constraint_flag"],
            "sps_sub_layer_max_8bit_constraint_flag":sps_rbsp.order["sub_layer_max_8bit_constraint_flag"],
            "sps_sub_layer_max_422chroma_constraint_flag":sps_rbsp.order["sub_layer_max_422chroma_constraint_flag"],
            "sps_sub_layer_max_420chroma_constraint_flag":sps_rbsp.order["sub_layer_max_420chroma_constraint_flag"],
            "sps_sub_layer_max_monochrome_constraint_flag":sps_rbsp.order["sub_layer_max_monochrome_constraint_flag"],
            "sps_sub_layer_intra_constraint_flag":sps_rbsp.order["sub_layer_intra_constraint_flag"],
            "sps_sub_layer_one_picture_only_constraint_flag_1":sps_rbsp.order["sub_layer_one_picture_only_constraint_flag_1"],
            "sps_sub_layer_lower_bit_rate_constraint_flag":sps_rbsp.order["sub_layer_lower_bit_rate_constraint_flag"],
            "sps_sub_layer_max_14bit_constraint_flag":sps_rbsp.order["sub_layer_max_14bit_constraint_flag"],
            "sps_sub_layer_reserved_zero_33bits":sps_rbsp.order["sub_layer_reserved_zero_33bits"],
            "sps_sub_layer_reserved_zero_34bits":sps_rbsp.order["sub_layer_reserved_zero_34bits"],
            "sps_sub_layer_reserved_zero_7bits":sps_rbsp.order["sub_layer_reserved_zero_7bits"],
            "sps_sub_layer_one_picture_only_constraint_flag_2":sps_rbsp.order["sub_layer_one_picture_only_constraint_flag_2"],
            "sps_sub_layer_reserved_zero_35bits":sps_rbsp.order["sub_layer_reserved_zero_35bits"],
            "sps_sub_layer_reserved_zero_43bits":sps_rbsp.order["sub_layer_reserved_zero_43bits"],
            "sps_sub_layer_inbld_flag":sps_rbsp.order["sub_layer_inbld_flag"],
            "sps_sub_layer_reserved_zero_bit":sps_rbsp.order["sub_layer_reserved_zero_bit"],
            "sps_sub_layer_level_idc":sps_rbsp.order["sub_layer_level_idc"],

            "sps_seq_parameter_set_id":sps_rbsp.order["sps_seq_parameter_set_id"],
            "chroma_format_idc":sps_rbsp.order["chroma_format_idc"],
            "separate_colour_plane_flag":sps_rbsp.order["separate_colour_plane_flag"],
            "pic_width_in_luma_samples":sps_rbsp.order["pic_width_in_luma_samples"],
            "pic_height_in_luma_samples":sps_rbsp.order["pic_height_in_luma_samples"],
            "conformance_window_flag":sps_rbsp.order["conformance_window_flag"],
            "conf_win_left_offset":sps_rbsp.order["conf_win_left_offset"],
            "conf_win_right_offset":sps_rbsp.order["conf_win_right_offset"],
            "conf_win_top_offset":sps_rbsp.order["conf_win_top_offset"],
            "conf_win_bottom_offset":sps_rbsp.order["conf_win_bottom_offset"],
            "bit_depth_luma_minus8":sps_rbsp.order["bit_depth_luma_minus8"],
            "bit_depth_chroma_minus8":sps_rbsp.order["bit_depth_chroma_minus8"],
            "log2_max_pic_order_cnt_lsb_minus4":sps_rbsp.order["log2_max_pic_order_cnt_lsb_minus4"],
            "sps_sub_layer_ordering_info_present_flag":sps_rbsp.order["sps_sub_layer_ordering_info_present_flag"],
            "sps_max_dec_pic_buffering_minus1":sps_rbsp.order["sps_max_dec_pic_buffering_minus1"],
            "sps_max_num_reorder_pics":sps_rbsp.order["sps_max_num_reorder_pics"],
            "sps_max_latency_increase_plus1":sps_rbsp.order["sps_max_latency_increase_plus1"],
            "log2_min_luma_coding_block_size_minus3":sps_rbsp.order["log2_min_luma_coding_block_size_minus3"],
            "log2_diff_max_min_luma_coding_block_size":sps_rbsp.order["log2_diff_max_min_luma_coding_block_size"],
            "log2_min_luma_transform_block_size_minus2":sps_rbsp.order["log2_min_luma_transform_block_size_minus2"],
            "log2_diff_max_min_luma_transform_block_size":sps_rbsp.order["log2_diff_max_min_luma_transform_block_size"],
            "max_transform_hierarchy_depth_inter":sps_rbsp.order["max_transform_hierarchy_depth_inter"],
            "max_transform_hierarchy_depth_intra":sps_rbsp.order["max_transform_hierarchy_depth_intra"],
            "scaling_list_enabled_flag":sps_rbsp.order["scaling_list_enabled_flag"],
            "sps_scaling_list_data_present_flag":sps_rbsp.order["sps_scaling_list_data_present_flag"],
            # sps -> scaling_list_data()
            "scaling_list_pred_mode_flag":sps_rbsp.order["scaling_list_pred_mode_flag"],
            "scaling_list_pred_matrix_id_delta":sps_rbsp.order["scaling_list_pred_matrix_id_delta"],
            "scaling_list_dc_coef_minus8":sps_rbsp.order["scaling_list_dc_coef_minus8"],
            "scaling_list_delta_coef":sps_rbsp.order["scaling_list_delta_coef"],

            "amp_enabled_flag":sps_rbsp.order["amp_enabled_flag"],
            "sample_adaptive_offset_enabled_flag":sps_rbsp.order["sample_adaptive_offset_enabled_flag"],
            "pcm_enabled_flag":sps_rbsp.order["pcm_enabled_flag"],
            "pcm_sample_bit_depth_luma_minus1":sps_rbsp.order["pcm_sample_bit_depth_luma_minus1"],
            "pcm_cample_bit_depth_chroma_minus1":sps_rbsp.order["pcm_cample_bit_depth_chroma_minus1"],
            "log2_min_pcm_luma_coding_block_size_minus3":sps_rbsp.order["log2_min_pcm_luma_coding_block_size_minus3"],
            "log2_diff_max_min_pcm_luma_coding_block_size":sps_rbsp.order["log2_diff_max_min_pcm_luma_coding_block_size"],
            "pcm_loop_filter_disabled_flag":sps_rbsp.order["pcm_loop_filter_disabled_flag"],
            "num_short_term_ref_pic_sets":sps_rbsp.order["num_short_term_ref_pic_sets"],
            # sps -> st_ref_pic_set()
            "inter_ref_pic_set_prediction_flag":sps_rbsp.order["inter_ref_pic_set_prediction_flag"],
            "delta_idx_minus1":sps_rbsp.order["delta_idx_minus1"],
            "delta_rps_sign":sps_rbsp.order["delta_rps_sign"],
            "abs_delta_rps_minus1":sps_rbsp.order["abs_delta_rps_minus1"],
            "used_by_curr_pic_flag":sps_rbsp.order["used_by_curr_pic_flag"],
            "use_delta_flag":sps_rbsp.order["use_delta_flag"],
            "num_negative_pics":sps_rbsp.order["num_negative_pics"],
            "num_positive_pics":sps_rbsp.order["num_positive_pics"],
            "delta_poc_s0_minus1":sps_rbsp.order["delta_poc_s0_minus1"],
            "used_by_curr_pic_s0_flag":sps_rbsp.order["used_by_curr_pic_s0_flag"],
            "delta_poc_s1_minus1":sps_rbsp.order["delta_poc_s1_minus1"],
            "used_by_curr_pic_s1_flag":sps_rbsp.order["used_by_curr_pic_s1_flag"],

            "long_term_ref_pics_present_flag":sps_rbsp.order["long_term_ref_pics_present_flag"],
            "num_long_term_ref_pics_sps":sps_rbsp.order["num_long_term_ref_pics_sps"],
            "lt_ref_pic_poc_lsb_sps":sps_rbsp.order["lt_ref_pic_poc_lsb_sps"],
            "used_by_curr_pic_lt_sps_flag":sps_rbsp.order["used_by_curr_pic_lt_sps_flag"],
            "sps_temporal_mvp_enabled_flag":sps_rbsp.order["sps_temporal_mvp_enabled_flag"],
            "strong_intra_smoothing_enabled_flag":sps_rbsp.order["strong_intra_smoothing_enabled_flag"],
            "vui_parameters_present_flag":sps_rbsp.order["vui_parameters_present_flag"],
            "vui":sps_rbsp.order["vui"],
            "sps_extension_present_flag":sps_rbsp.order["sps_extension_present_flag"],
            "sps_range_extension_flag":sps_rbsp.order["sps_range_extension_flag"],
            "sps_multilayer_extension_flag":sps_rbsp.order["sps_multilayer_extension_flag"],
            "sps_3d_extension_flag":sps_rbsp.order["sps_3d_extension_flag"],
            "sps_scc_extension_flag":sps_rbsp.order["sps_scc_extension_flag"],
            "sps_extension_4bits":sps_rbsp.order["sps_extension_4bits"],
            # sps->sps_range_extension()
            "transform_skip_rotation_enabled_flag":sps_rbsp.order["transform_skip_rotation_enabled_flag"],
            "transform_skip_content_enabled_flag":sps_rbsp.order["transform_skip_content_enabled_flag"],
            "implicit_rdpcm_enabled_flag":sps_rbsp.order["implicit_rdpcm_enabled_flag"],
            "explicit_rdpcm_enabled_flag":sps_rbsp.order["explicit_rdpcm_enabled_flag"],
            "intra_smoothing_disabled_flag":sps_rbsp.order["intra_smoothing_disabled_flag"],
            "high_precision_offsets_enabled_flag":sps_rbsp.order["high_precision_offsets_enabled_flag"],
            "persistent_rice_adaptation_enabled_flag":sps_rbsp.order["persistent_rice_adaptation_enabled_flag"],
            "cabac_bypass_alignment_enabled_flag":sps_rbsp.order["cabac_bypass_alignment_enabled_flag"],
            # sps->sps_multilayer_extension()
            "inter_view_mv_vert_constraint_flag":sps_rbsp.order["inter_view_mv_vert_constraint_flag"],
            # sps->sps_3d_extension()
            "iv_di_mc_enabled_flag":sps_rbsp.order["iv_di_mc_enabled_flag"],
            "iv_mv_scal_enabled_flag":sps_rbsp.order["iv_mv_scal_enabled_flag"],
            "log2_ivmc_sub_pb_size_minus3":sps_rbsp.order["log2_ivmc_sub_pb_size_minus3"],
            "iv_res_pred_enabled_flag":sps_rbsp.order["iv_res_pred_enabled_flag"],
            "depth_ref_enabled_flag":sps_rbsp.order["depth_ref_enabled_flag"],
            "vsp_mc_enabled_flag":sps_rbsp.order["vsp_mc_enabled_flag"],
            "dbbp_enabled_flag":sps_rbsp.order["dbbp_enabled_flag"],
            "tex_mc_enabled_flag":sps_rbsp.order["tex_mc_enabled_flag"],
            "log2_texmc_sub_pb_size_minus3":sps_rbsp.order["log2_texmc_sub_pb_size_minus3"],
            "intra_contour_enabled_flag":sps_rbsp.order["intra_contour_enabled_flag"],
            "intra_dc_only_wedge_enabled_flag":sps_rbsp.order["intra_dc_only_wedge_enabled_flag"],
            "cqt_cu_part_pred_enabled_flag":sps_rbsp.order["cqt_cu_part_pred_enabled_flag"],
            "inter_dc_only_enabled_flag":sps_rbsp.order["inter_dc_only_enabled_flag"],
            "skip_intra_enabled_flag":sps_rbsp.order["skip_intra_enabled_flag"],
            # sps->sps_scc_extension()
            "sps_curr_pic_ref_enabled_flag":sps_rbsp.order["sps_curr_pic_ref_enabled_flag"],
            "palette_mode_enabled_flag":sps_rbsp.order["palette_mode_enabled_flag"],
            "palette_max_size":sps_rbsp.order["palette_max_size"],
            "delta_palette_max_predictor_size":sps_rbsp.order["delta_palette_max_predictor_size"],
            "sps_palette_predictor_initializers_present_flag":sps_rbsp.order["sps_palette_predictor_initializers_present_flag"],
            "sps_num_palette_predictor_initializers_minus1":sps_rbsp.order["sps_num_palette_predictor_initializers_minus1"],
            "sps_palette_predictor_initializer":sps_rbsp.order["sps_palette_predictor_initializer"],
            "motion_vector_resolution_control_idc":sps_rbsp.order["motion_vector_resolution_control_idc"],
            "intra_boundary_filtering_disabled_flag":sps_rbsp.order["intra_boundary_filtering_disabled_flag"],
        
            "sps_extension_data_flag":sps_rbsp.order["sps_extension_data_flag"],

            # VUI
            "aspect_ratio_info_present_flag":sps_rbsp.vui.order["aspect_ratio_info_present_flag"],
            "aspect_ratio_idc":sps_rbsp.vui.order["aspect_ratio_idc"],
            "sar_width":sps_rbsp.vui.order["sar_width"],
            "sar_height":sps_rbsp.vui.order["sar_height"],
            "overscan_info_present_flag":sps_rbsp.vui.order["overscan_info_present_flag"],
            "overscan_appropriate_flag":sps_rbsp.vui.order["overscan_appropriate_flag"],
            "video_signal_type_present_flag":sps_rbsp.vui.order["video_signal_type_present_flag"],
            "video_format":sps_rbsp.vui.order["video_format"],
            "video_full_range_flag":sps_rbsp.vui.order["video_full_range_flag"],
            "colour_description_present_flag":sps_rbsp.vui.order["colour_description_present_flag"],
            "colour_primaries":sps_rbsp.vui.order["colour_primaries"],
            "transfer_characteristics":sps_rbsp.vui.order["transfer_characteristics"],
            "matrix_coefficients":sps_rbsp.vui.order["matrix_coefficients"],
            "chroma_loc_info_present_flag":sps_rbsp.vui.order["chroma_loc_info_present_flag"],
            "chroma_sample_loc_type_top_field":sps_rbsp.vui.order["chroma_sample_loc_type_top_field"],
            "chroma_sample_loc_type_bottom_field":sps_rbsp.vui.order["chroma_sample_loc_type_bottom_field"],
            "neutral_chroma_indication_flag":sps_rbsp.vui.order["neutral_chroma_indication_flag"],
            "field_seq_flag":sps_rbsp.vui.order["field_seq_flag"],
            "frame_field_info_present_flag":sps_rbsp.vui.order["frame_field_info_present_flag"],
            "default_display_window_flag":sps_rbsp.vui.order["default_display_window_flag"],
            "def_disp_win_left_offset":sps_rbsp.vui.order["def_disp_win_left_offset"],
            "def_disp_win_right_offset":sps_rbsp.vui.order["def_disp_win_right_offset"],
            "def_disp_win_top_offset":sps_rbsp.vui.order["def_disp_win_top_offset"],
            "def_disp_win_bottom_offset":sps_rbsp.vui.order["def_disp_win_bottom_offset"],
            "vui_timing_info_present_flag":sps_rbsp.vui.order["vui_timing_info_present_flag"],
            "vui_num_units_in_tick":sps_rbsp.vui.order["vui_num_units_in_tick"],
            "vui_time_scale":sps_rbsp.vui.order["vui_time_scale"],
            "vui_poc_proportional_to_timing_flag":sps_rbsp.vui.order["vui_poc_proportional_to_timing_flag"],
            "vui_num_ticks_poc_diff_one_minus1":sps_rbsp.vui.order["vui_num_ticks_poc_diff_one_minus1"],
            "vui_hrd_parameters_present_flag":sps_rbsp.vui.order["vui_hrd_parameters_present_flag"],
            #vui -> hrd_parameters()

            "bitstream_restriction_flag":sps_rbsp.vui.order["bitstream_restriction_flag"],
            "tiles_fixed_structure_flag":sps_rbsp.vui.order["tiles_fixed_structure_flag"],
            "motion_vectors_over_pic_boundaries_flag":sps_rbsp.vui.order["motion_vectors_over_pic_boundaries_flag"],
            "restricted_ref_pic_lists_flag":sps_rbsp.vui.order["restricted_ref_pic_lists_flag"],
            "min_spatial_segmentation_idc":sps_rbsp.vui.order["min_spatial_segmentation_idc"],
            "max_bytes_per_pic_denom":sps_rbsp.vui.order["max_bytes_per_pic_denom"],
            "max_bits_per_min_cu_denom":sps_rbsp.vui.order["max_bits_per_min_cu_denom"],
            "log2_max_mv_length_horizontal":sps_rbsp.vui.order["log2_max_mv_length_horizontal"],
            "log2_max_mv_length_vertical":sps_rbsp.vui.order["log2_max_mv_length_vertical"],

            # PPS
            "pps_pic_parameter_set_id":pps_rbsp.order["pps_pic_parameter_set_id"],
            "pps_seq_parameter_set_id":pps_rbsp.order["pps_seq_parameter_set_id"],
            "dependent_slice_segments_enabled_flag":pps_rbsp.order["dependent_slice_segments_enabled_flag"],
            "output_flag_present_flag":pps_rbsp.order["output_flag_present_flag"],
            "num_extra_slice_header_bits":pps_rbsp.order["num_extra_slice_header_bits"],
            "sign_data_hiding_enabled_flag":pps_rbsp.order["sign_data_hiding_enabled_flag"],
            "cabac_init_present_flag":pps_rbsp.order["cabac_init_present_flag"],
            "num_ref_idx_l0_default_active_minus1":pps_rbsp.order["num_ref_idx_l0_default_active_minus1"],
            "num_ref_idx_l1_default_active_minus1":pps_rbsp.order["num_ref_idx_l1_default_active_minus1"],
            "init_qp_minus26":pps_rbsp.order["init_qp_minus26"],
            "constrained_intra_pred_flag":pps_rbsp.order["constrained_intra_pred_flag"],
            "transform_skip_enabled_flag":pps_rbsp.order["transform_skip_enabled_flag"],
            "cu_qp_delta_enabled_flag":pps_rbsp.order["cu_qp_delta_enabled_flag"],
            "diff_cu_qp_delta_depth":pps_rbsp.order["diff_cu_qp_delta_depth"],
            "pps_cb_qp_offset":pps_rbsp.order["pps_cb_qp_offset"],
            "pps_cr_qp_offset":pps_rbsp.order["pps_cr_qp_offset"],
            "pps_slice_chroma_qp_offsets_present_flag":pps_rbsp.order["pps_slice_chroma_qp_offsets_present_flag"],
            "weighted_pred_flag":pps_rbsp.order["weighted_pred_flag"],
            "weighted_bipred_flag":pps_rbsp.order["weighted_bipred_flag"],
            "transquant_bypass_enabled_flag":pps_rbsp.order["transquant_bypass_enabled_flag"],
            "tiles_enabled_flag":pps_rbsp.order["tiles_enabled_flag"],
            "entropy_coding_sync_enabled_flag":pps_rbsp.order["entropy_coding_sync_enabled_flag"],
            "num_tile_columns_minus1":pps_rbsp.order["num_tile_columns_minus1"],
            "num_tile_rows_minus1":pps_rbsp.order["num_tile_rows_minus1"],
            "uniform_spacing_flag":pps_rbsp.order["uniform_spacing_flag"],
            "column_width_minus1":pps_rbsp.order["column_width_minus1"],
            "row_height_minus1":pps_rbsp.order["row_height_minus1"],
            "loop_filter_across_tiles_enabled_flag":pps_rbsp.order["loop_filter_across_tiles_enabled_flag"],
            "pps_loop_filter_across_slices_enabled_flag":pps_rbsp.order["pps_loop_filter_across_slices_enabled_flag"],
            "deblocking_filter_control_present_flag":pps_rbsp.order["deblocking_filter_control_present_flag"],
            "deblocking_filter_override_enabled_flag":pps_rbsp.order["deblocking_filter_override_enabled_flag"],
            "pps_deblocking_filter_disabled_flag":pps_rbsp.order["pps_deblocking_filter_disabled_flag"],
            "pps_beta_offset_div2":pps_rbsp.order["pps_beta_offset_div2"],
            "pps_tc_offset_div2":pps_rbsp.order["pps_tc_offset_div2"],
            "pps_scaling_list_data_present_flag":pps_rbsp.order["pps_scaling_list_data_present_flag"],
            # pps->scaling_list_data()

            "lists_modification_present_flag":pps_rbsp.order["lists_modification_present_flag"],
            "log2_parallel_merge_level_minus2":pps_rbsp.order["log2_parallel_merge_level_minus2"],
            "slice_segment_header_extension_present_flag":pps_rbsp.order["slice_segment_header_extension_present_flag"],
            "pps_extension_present_flag":pps_rbsp.order["pps_extension_present_flag"],
            "pps_range_extension_flag":pps_rbsp.order["pps_range_extension_flag"],
            "pps_multilayer_extension_flag":pps_rbsp.order["pps_multilayer_extension_flag"],
            "pps_3d_extension_flag":pps_rbsp.order["pps_3d_extension_flag"],
            "pps_scc_extension_flag":pps_rbsp.order["pps_scc_extension_flag"],
            "pps_extension_4bits":pps_rbsp.order["pps_extension_4bits"],
            # pps -> pps_range_extension()
            "log2_max_transform_skip_block_size_minus2":pps_rbsp.order["log2_max_transform_skip_block_size_minus2"],
            "cross_component_prediction_enabled_flag":pps_rbsp.order["cross_component_prediction_enabled_flag"],
            "chroma_qp_offset_list_enabled_flag":pps_rbsp.order["chroma_qp_offset_list_enabled_flag"],
            "diff_cu_chroma_qp_offset_depth":pps_rbsp.order["diff_cu_chroma_qp_offset_depth"],
            "chroma_qp_offset_list_len_minus1":pps_rbsp.order["chroma_qp_offset_list_len_minus1"],
            "cb_qp_offset_list":pps_rbsp.order["cb_qp_offset_list"],
            "cr_qp_offset_list":pps_rbsp.order["cr_qp_offset_list"],
            "log2_sao_offset_scale_luma":pps_rbsp.order["log2_sao_offset_scale_luma"],
            "log2_sao_offset_scale_chroma":pps_rbsp.order["log2_sao_offset_scale_chroma"],
            # pps -> pps_multilayer_extension()
            "poc_reset_info_present_flag":pps_rbsp.order["poc_reset_info_present_flag"],
            "pps_infer_scaling_list_flag":pps_rbsp.order["pps_infer_scaling_list_flag"],
            "pps_scaling_list_ref_layer_id":pps_rbsp.order["pps_scaling_list_ref_layer_id"],
            "num_ref_loc_offsets":pps_rbsp.order["num_ref_loc_offsets"],
            "ref_loc_offset_layer_id":pps_rbsp.order["ref_loc_offset_layer_id"],
            "scaled_ref_layer_offset_present_flag":pps_rbsp.order["scaled_ref_layer_offset_present_flag"],
            "scaled_ref_layer_left_offset":pps_rbsp.order["scaled_ref_layer_left_offset"],
            "scaled_ref_layer_top_offset":pps_rbsp.order["scaled_ref_layer_top_offset"],
            "scaled_ref_layer_right_offset":pps_rbsp.order["scaled_ref_layer_right_offset"],
            "scaled_ref_layer_bottom_offset":pps_rbsp.order["scaled_ref_layer_bottom_offset"],
            "ref_region_offset_present_flag":pps_rbsp.order["ref_region_offset_present_flag"],
            "ref_region_left_offset":pps_rbsp.order["ref_region_left_offset"],
            "ref_region_top_offset":pps_rbsp.order["ref_region_top_offset"],
            "ref_region_right_offset":pps_rbsp.order["ref_region_right_offset"],
            "ref_region_bottom_offset":pps_rbsp.order["ref_region_bottom_offset"],
            "resample_phase_set_present_flag":pps_rbsp.order["resample_phase_set_present_flag"],
            "phase_hor_luma":pps_rbsp.order["phase_hor_luma"],
            "phase_ver_luma":pps_rbsp.order["phase_ver_luma"],
            "phase_hor_chroma_plus8":pps_rbsp.order["phase_hor_chroma_plus8"],
            "phase_ver_chroma_plus8":pps_rbsp.order["phase_ver_chroma_plus8"],
            "colour_mapping_enabled_flag":pps_rbsp.order["colour_mapping_enabled_flag"],
            # pps-> pps_multilayer_extension() ->colour_mapping_table()
            "num_cm_ref_layers_minus1":pps_rbsp.order["num_cm_ref_layers_minus1"],
            "cm_ref_layer_id":pps_rbsp.order["cm_ref_layer_id"],
            "cm_octant_depth":pps_rbsp.order["cm_octant_depth"],
            "cm_y_part_num_log2":pps_rbsp.order["cm_y_part_num_log2"],
            "luma_bit_depth_cm_input_minus8":pps_rbsp.order["luma_bit_depth_cm_input_minus8"],
            "chroma_bit_depth_cm_input_minus8":pps_rbsp.order["chroma_bit_depth_cm_input_minus8"],
            "luma_bit_depth_cm_output_minus8":pps_rbsp.order["luma_bit_depth_cm_output_minus8"],
            "chroma_bit_depth_cm_output_minus8":pps_rbsp.order["chroma_bit_depth_cm_output_minus8"],
            "cm_res_quant_bits":pps_rbsp.order["cm_res_quant_bits"],
            "cm_delta_flc_bits_minus1":pps_rbsp.order["cm_delta_flc_bits_minus1"],
            "cm_adapt_threshold_u_delta":pps_rbsp.order["cm_adapt_threshold_u_delta"],
            "cm_adapt_threshold_v_delta":pps_rbsp.order["cm_adapt_threshold_v_delta"],
            # pps-> pps_multilayer_extension() ->colour_mapping_table()->colour_mapping_octants()

            #pps->pps_3d_extension()
            "dlts_present_flag":pps_rbsp.order["dlts_present_flag"],
            "pps_depth_layers_minus1":pps_rbsp.order["pps_depth_layers_minus1"],
            "pps_bit_depth_for_depth_layers_minus8":pps_rbsp.order["pps_bit_depth_for_depth_layers_minus8"],
            "dlt_flag":pps_rbsp.order["dlt_flag"],
            "dlt_pred_flag":pps_rbsp.order["dlt_pred_flag"],
            "dlt_val_flags_present_flag":pps_rbsp.order["dlt_val_flags_present_flag"],
            "dlt_value_flag":pps_rbsp.order["dlt_value_flag"],
            "num_val_delta_dlt":pps_rbsp.order["num_val_delta_dlt"],
            "max_diff":pps_rbsp.order["max_diff"],
            "min_diff_minus1":pps_rbsp.order["min_diff_minus1"],
            "delta_dlt_val0":pps_rbsp.order["delta_dlt_val0"],
            "delta_val_diff_minus_min":pps_rbsp.order["delta_val_diff_minus_min"]
            #pps->pps_scc_extension(), pps_extension_4bits
            #"pps_extension_data_flag":pps_rbsp.order["pps_extension_data_flag"]
        }

        df = pd.DataFrame([result], index=[0])
        df = df.fillna("-9999")

        if not os.path.exists('NALUFeature_h265.csv'):
            df.to_csv('NALUFeature_h265.csv', index=False, mode='w', encoding='utf-8-sig', header=True)
        else:
            df.to_csv('NALUFeature_h265.csv', index=False, mode='a', encoding='utf-8-sig', header=False)


codec_check = videoParsing(video_path, AtomDict)

if codec_check == "avc1":
    sps_rbsp, pps_rbsp = getNALU(AtomDict, codec_check)
    h264NALUExtraction(video_path,sps_rbsp, pps_rbsp)
else:
    vps_rbsp, sps_rbsp, pps_rbsp = getNALU(AtomDict, codec_check)
    h265NALUExtraction(video_path, vps_rbsp, sps_rbsp, pps_rbsp)

# sys.stdout.close()

# video_path = sys.argv[1]
# NALUExtraction(video_path)